# Generated by Django 2.1.7 on 2019-03-07 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minerals_app', '0002_minerals_diaphaneity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minerals',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='minerals',
            name='diagphaneity',
        ),
    ]
